import globals from 'globals';
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";

export default [
    pluginJs.configs.all,
    ...tseslint.configs.all,
    {
        files: ['**/*.{js,mjs,cjs,ts}'],
        languageOptions: {
            globals: globals.browser,
            parserOptions: {
                project: './tsconfig.json'
            }
        },
        rules: {
            '@typescript-eslint/ban-tslint-comment': 'off',
            '@typescript-eslint/class-methods-use-this': 'warn',
            '@typescript-eslint/consistent-indexed-object-style': ['error', 'index-signature'],
            '@typescript-eslint/consistent-type-definitions': ['warn', 'type'],
            '@typescript-eslint/consistent-type-imports': 'warn',
            '@typescript-eslint/explicit-function-return-type': 'off',
            '@typescript-eslint/explicit-member-accessibility': 'off',
            '@typescript-eslint/explicit-module-boundary-types': 'off',
            '@typescript-eslint/indent': 'off',
            '@typescript-eslint/init-declarations': 'off',
            '@typescript-eslint/lines-between-class-members': 'off',
            '@typescript-eslint/max-params': 'off',
            '@typescript-eslint/member-ordering': 'warn',
            '@typescript-eslint/method-signature-style': ['warn', 'method'],
            '@typescript-eslint/naming-convention': 'off',
            '@typescript-eslint/no-confusing-void-expression': ['warn', {ignoreArrowShorthand: true}],
            '@typescript-eslint/no-dynamic-delete': 'warn',
            '@typescript-eslint/no-empty-function': 'off',
            '@typescript-eslint/no-floating-promises': 'warn',
            '@typescript-eslint/no-inferrable-types': 'warn',
            '@typescript-eslint/no-invalid-void-type': 'off',
            '@typescript-eslint/no-loop-func': 'warn',
            '@typescript-eslint/no-magic-numbers': 'off',
            '@typescript-eslint/no-misused-promises': 'warn',
            '@typescript-eslint/no-shadow': 'off',
            '@typescript-eslint/no-type-alias': 'off',
            '@typescript-eslint/no-unnecessary-condition': 'warn',
            '@typescript-eslint/no-unnecessary-template-expression': 'warn',
            '@typescript-eslint/no-unsafe-call': 'warn',
            '@typescript-eslint/no-unused-expressions': 'warn',
            '@typescript-eslint/no-unused-vars': 'off',
            '@typescript-eslint/no-use-before-define': 'warn',
            '@typescript-eslint/object-curly-spacing': 'off',
            '@typescript-eslint/prefer-for-of': 'warn',
            '@typescript-eslint/prefer-nullish-coalescing': 'warn',
            '@typescript-eslint/prefer-optional-chain': 'warn',
            '@typescript-eslint/prefer-readonly-parameter-types': 'off',
            '@typescript-eslint/promise-function-async': 'off',
            '@typescript-eslint/require-array-sort-compare': ['warn', {ignoreStringArrays: true}],
            '@typescript-eslint/require-await': 'off',
            '@typescript-eslint/restrict-template-expressions': 'off',
            '@typescript-eslint/return-await': 'warn',
            '@typescript-eslint/sort-type-constituents': 'warn',
            '@typescript-eslint/strict-boolean-expressions': 'off',
            '@typescript-eslint/unbound-method': 'off',
            '@typescript-eslint/use-unknown-in-catch-callback-variable': 'off',
            'array-bracket-newline': 'off',
            'array-element-newline': 'off',
            'arrow-body-style': 'warn',
            'arrow-parens': 'off',
            'arrow-spacing': 'warn',
            'block-spacing': 'warn',
            'brace-style': 'warn',
            'camelcase': 'off',
            'capitalized-comments': 'off',
            'class-methods-use-this': 'off',
            'comma-dangle': 'warn',
            'comma-spacing': 'warn',
            'comma-style': 'warn',
            'complexity': 'off',
            'curly': 'warn',
            'dot-location': ['error', 'property'],
            'eol-last': 'warn',
            'eqeqeq': 'warn',
            'func-call-spacing': 'warn',
            'func-names': 'warn',
            'func-style': ['warn', 'declaration'],
            'function-call-argument-newline': 'off',
            'function-paren-newline': 'off',
            'generator-star-spacing': ['warn', {before: false, after: true}],
            'id-length': 'off',
            'implicit-arrow-linebreak': 'off',
            'key-spacing': 'warn',
            'keyword-spacing': 'warn',
            'line-comment-position': 'off',
            'linebreak-style': 'off',
            'max-classes-per-file': 'off',
            'max-depth': 'off',
            'max-len': 'off',
            'max-lines': 'off',
            'max-lines-per-function': 'off',
            'max-params': 'off',
            'max-statements': 'off',
            'max-statements-per-line': 'warn',
            'multiline-comment-style': 'off',
            'multiline-ternary': 'off',
            'new-cap': 'warn',
            'newline-per-chained-call': 'off',
            'no-alert': 'off',
            'no-await-in-loop': 'off',
            'no-bitwise': 'off',
            'no-confusing-arrow': 'off',
            'no-console': 'off',
            'no-constant-binary-expression': 'warn',
            'no-constant-condition': 'warn',
            'no-continue': 'off',
            'no-debugger': 'warn',
            'no-else-return': 'warn',
            'no-empty': 'warn',
            'no-eq-null': 'warn',
            'no-extra-parens': 'warn',
            'no-extra-semi': 'warn',
            'no-inline-comments': 'off',
            'no-inner-declarations': 'off',
            'no-lone-blocks': 'warn',
            'no-mixed-operators': 'off',
            'no-multi-spaces': ['warn', {ignoreEOLComments: true}],
            'no-multiple-empty-lines': ['warn', {max: 1}],
            'no-nested-ternary': 'off',
            'no-new': 'warn',
            'no-param-reassign': 'off',
            'no-plusplus': 'off',
            'no-prototype-builtins': 'off',
            'no-return-assign': 'off',
            'no-ternary': 'off',
            'no-trailing-spaces': 'warn',
            'no-undefined': 'off',
            'no-underscore-dangle': 'off',
            'no-unreachable-loop': 'warn',
            'no-useless-assignment': 'warn',
            'no-warning-comments': 'off',
            'no-whitespace-before-property': 'warn',
            'nonblock-statement-body-position': 'warn',
            'object-curly-newline': 'warn',
            'object-property-newline': 'off',
            'object-shorthand': 'warn',
            'one-var': ['warn', 'never'],
            'operator-linebreak': 'warn',
            'ordered-imports': 'off',
            'padded-blocks': ['warn', 'never'],
            'prefer-arrow-callback': 'warn',
            'prefer-const': 'warn',
            'prefer-destructuring': 'warn',
            'prefer-named-capture-group': 'off',
            'prefer-rest-params': 'off',
            'prefer-template': 'warn',
            'quote-props': ['warn', 'as-needed'],
            'quotes': ['warn', 'single'],
            'radix': 'off',
            'require-unicode-regexp': 'off',
            'semi': 'warn',
            'semi-style': 'warn',
            'sort-imports': ['warn', {
                ignoreCase: true,
                ignoreDeclarationSort: true,
                ignoreMemberSort: false,
                memberSyntaxSortOrder: ['none', 'all', 'single', 'multiple'],
                allowSeparatedGroups: false,
            }],
            'sort-keys': 'off',
            'space-before-blocks': 'warn',
            'space-before-function-paren': ['warn', {
                anonymous: 'always',
                named: 'never',
                asyncArrow: 'always'
            }],
            'space-in-parens': 'warn',
            'space-infix-ops': 'warn',
            'space-unary-ops': 'warn',
            'spaced-comment': 'warn',
            'wrap-regex': 'off'
        }
    }
];
